name: Deploy

on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate on GCP
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Download built folders
        uses: actions/download-artifact@v2
        with:
          name: built
          path: build
      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/festive-utility-343713/brdevstreamers-ui:${{ github.sha }} .
          docker push gcr.io/festive-utility-343713/brdevstreamers-ui:${{ github.sha }}
      - name: Deploy
        id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "brdevstreamers-ui"
          image: "gcr.io/festive-utility-343713/brdevstreamers-ui:${{ github.sha }}"
      - name: "Use output" 
        run: 'curl "${{ steps.deploy.outputs.url }}"'
